jondot/hygen

content/docs/introduction.md
The instruction for initializing in the project were simply reversed.  The error that is thrown tells you to use it the other way around.
=> Reversed the instruction for self init

src/__tests__/metaverse.spec.js, src/__tests__/metaverse/hygen-templates/_templates/add-unless-exists/new/always.ejs.t, src/__tests__/metaverse/hygen-templates/_templates/add-unless-exists/new/y_overwrite.ejs.t, src/__tests__/metaverse/hygen-templates/_templates/add-unless-exists/new/z_dont-overwrite.ejs.t, src/__tests__/metaverse/hygen-templates/expected/add-unless-exists/foo/always.txt, src/ops/add.js
Added a feature to the add operation to only execute unless the file already exists.
When generating code it is necessary to not only generate the new code but also use injections to "register" it in other parts of the application. This works fine by using the inject feature. 
But it only works correctly when the target file with the base structure is already there, which is not ensured. 
In these cases someone would like to write a template that ensures the scaffold is produced before and do the injection in another template for the actual "registration". 
**For example:**
Assume you have the following application structure:
```
app
├ modules
├ my_module
├ controllers
├ controllerA.js
├ tests
├ suite.js
├ controllerA.spec.js
```
Its easy to build a generator that creates a new …
=> feature: add unless exists option to add operation

README.md
Using githubusercontent urls so that images on https://www.npmjs.com/package/hygen are not broken anymore
=> docs: Fixed image links in readme

content/docs/create.md
Added ```create.md``` into the content/docs directory -- hope that's the right thing to do.  It seemed to work well when I ran ```yarn docs:watch``` (i.e., the new page showed up), but since I'm not familiar with Gatsby I may have missed some key points.  Please let me know if I should change anything.
I opted to keep the description at a very high level, and leave the details in the project's README file. This way I won't have to bother you with a PR every time a make a small change to the documentation - only when there's something major.
=> Docs: added "Ecosystem" reference to hygen-create

content/docs/introduction.md, content/docs/templates.md
So, just started to use your awesome creation!
And as I traversed through the docs found those two issue and fixed in a blink.
Also, maybe the menu order is fliped? Right now the _Templates_ are the 2nd menu item, even tho it feels like you have to read about _Generators_ first to understand what's happening, and there is a line in the generators docs 
> We'll see more of these in templates.
So, I think this order would be more suitable.
- Quick Start
- Generators
- Templates
Cheers, and keep up this good work! Gona contrib later as I get more used to the library, already has some idea to implement ;)
=> Fix at_line reference & add missing generator in the docs

src/__tests__/__snapshots__/injector.spec.js.snap, src/__tests__/injector.spec.js, src/ops/injector.js
Hello!
I feeling some pain because my editor paste empty line on the end of file after save and after injection I recieving terrible files.
```css
@import 'foo'
/* Inject here */
@import 'baz' /* injected */
@import 'bar'
```
So, I think `eof_last` attribute must be really useful. If you set `false` to it, empty line at the end of injection body will be removed.
For example:
```
---
to: main.css
inject: true
after: \/\* Inject here \*\/
eof_last: false
---
```
Result must be like this:
```
```css
@import 'foo'
/* Inject here */
@import 'baz' /* injected */
@import 'bar'
```
=> Add eof_last attribute to inject options

content/docs/faq.md, src/__tests__/__snapshots__/injector.spec.js.snap, src/__tests__/injector.spec.js, src/ops/injector.js
This is just my quick crack at it.  Here are some notes:
- to ensure backwards-compatibility, the injector will use the existing line-by-line match behavior, and only use the new full-text matching behavior if the existing behavior does not match.
- the first thing the new matching does is `join` the lines back up again, which is inefficient; it would be much more reasonable to pass the original `content` into `indexByLocation`.  I just wanted to have as little/clear of a footprint as possible for this PR, so I didn't change that call signature, but you will probably want to do so. 
- The `skip_if` aspect of the support was a simple change that could have been done independently; as far as I could see, there wasn't any particular reason to be doing a lodash find of a regex match on each …
=> support for matching `before`, `after`, and `skip_if` attributes that span newlines

src/__tests__/fixtures/app/action-multifiles-nest/arbitrarySubfolder/capitalized.ejs.t, src/__tests__/fixtures/app/action-multifiles-nest/full.ejs.t, src/__tests__/render.spec.js, src/render.js
This PR should allow an arbitrary directory structure below the action subfolder for templates, so that users have more options to organize their files.
I shamelessly ~stole~borrowed the core of this change from [this StackOverflow answer](https://stackoverflow.com/a/45130990).  
I don't think this will cause any significant performance issues (but I didn't do any large-load perf testing or anything... ymmv).
This would satisfy #28.
Note: I also added a couple of TODOs for some extra tests of unrelated functionality that should probably be added (only because I almost committed this without those lines, and the test suite didn't complain), but I didn't actually write those tests myself, because I'm lazy. 😄
=> recurse template subdirectories

src/engine.js
```
[~/code/workspace/hygen] cli-help+ ± yarn hygen --help       
Usage:
hygen [option] GENERATOR ACTION [--name NAME] [data-options]
Options:
-h, --help # Show this message and quit
--dry      # Perform a dry run.  Files will be generated but not saved.
```
`-h` works as well`
=> add usage msg

src/render.ts
=> [fix] adds back support for falsy front matter values e.g. eof_last

src/index.ts
My team enjoys seeing stack traces by default in our cli tools, especially when they point back to our prompt code. 
This change would allow us to set debug via `.hygen.js`
=> Allow debug to be driven by the resolvedConfig

src/ops/add.ts, src/ops/inject.ts
Using Hygen with Lerna in a multi package repo works great except for one small problem.
When executing a sub package script that uses Hygen from the root folder (via lerna run). The filename that is outputted to the terminal is relative to the sub-package. This means code editors like VS code that enable quick linking to files do not work.
* Add environment variable HYGEN_OUTPUT_ABS_PATH. 
* This variable is used to determine whether to display absolute or relative file paths when outputting generated filenames to the terminal
=> Ability to output abs path of generated files to terminal (useful for lerna, etc.)

package.json, src/__tests__/render.spec.ts, src/context.ts, src/types.ts, yarn.lock
It would be really useful to be able to define default values for parameters (locals) in the config file: **.hygen.js**
Right now only way to pass default parameters is by defining them as helpers:
`module.exports = {
helpers: { defaults: { name: "default" } }
}`
And in template use them as:
`<%= name || h.defaults.name %>`
=> feat: add locals defaults to config

package.json
Having `ts-jest` in `"dependencies"` includes it in the published version of this package. As far as I can tell, this package is only using `ts-jest` for tests. So this PR moves it to `devDependencies`.
We use Hygen at Airbnb, and this is blocking us from updating jest to v25.1.0 due to an unmet peer dependency from this package. 
```
Airbnb@1.0.0 /Users/sharmila_jesupaul/airlab/repos/airbnb-1
├─┬ hygen@5.0.1
│ └── ts-jest@24.3.0
└── ts-jest@25.2.0
npm ERR! peer dep missing: jest@>=24 <25, required by ts-jest@24.3.0
```
@jondot
=> [chore] Move ts-jest to dev dependencies

src/ops/shell.ts
This will allow to chain hygen commands and have them exit on error.
E.g.
hygen generate test && hygen make cake
If the first fails, the second will not run.
=> Exit hygen on shell command error

src/ops/injector.ts
At the moment, when hygen injects a file, it saves it with a Linux end of line (LF, \n). The next time that hygen will try to re-inject this file, it will split the content with the windows end of line (CRLF, \r\n) so it will fail to find the right line!
=> Fix #288 issue 

src/ops/injector.ts
Before files were split by the OS default line ending symbol. This caused trouble when running on a file that uses line ending symbols other than the default OS symbol, e. g. checking out files with LF ending via git on Windows. Instead, split by both line endings.
This is based on the discussion in #255 and the solution found by @HuynhTrongNgoan.
=> Split files by Windows/Unix line ending

lib/logger.js
Seems there was a breaking change in the chalk dependency which moved/renamed the [templates file here](https://github.com/chalk/chalk/commit/655653bb0c88fb05f839d5027f79751449771ec4#diff-3aa187c5a65150da43420c7f80d874cc)
This fixes it so it matches the updated path
=> fix(deps): fix chalk template path

src/prompt.ts, src/render.ts
=> Lazily support TS hook files

hygen.io/src/css/custom.css, hygen.io/src/pages/index.js
Hey, thanks for the cool library!
I've just started using it and I found some minor colours issues in the documentation and I would like to contribute fixing it.
Before:
Now:
Before:
Now:
=> Fix documentation colours for dark mode

dist/logger.js
https://github.com/jondot/hygen/pull/248 fixed a change in Chalk that meant `template` wasn't resolving, but this second copy of the same file was missed, which leads to the command-line help, for example: `hygen generator help`, to not properly render chalk sequences.
=> PR #248 missed this Chalk reference in its fix

src/render.ts
I recently experienced an error like: 
YAMLException: unexpected end of the stream within a double quoted scalar at line 2, column 1:
^
I had to debug the render.js script to figure out which file was having an issue, having this would have made it much easier to figure out what was wrong.
=> add debug logging during render

src/ops/echo.ts, src/ops/index.ts
Adding an echo command which can be used instead of `sh: echo "blabla"`
`echo:` runs before any shell command, in case you want to notify the user of a longer running operation.
```yaml
---
echo: This is a test of {inverse inverse}. It should run before the shell command is executed
sh: do some long operation like npm install
message: This shows when the shell command is finished
---
```
Also suppots multiline
```yaml
---
echo: |
some multiline
comment
which renders
as multiple lines
---
```
=> Add echo: command -> ops

src/prompt.ts
Add `prompt.cjs` to hooksfiles array for use with code bases using `type:module` in their `package.json` file
=> add prompt.cjs to hooksfiles array

README.md
Version 6.2.0 changed some files around in the npm package. The `lib` directory has been superseded by the `dist` directory, and `Logger` itself is not a constructor. These were the changes I needed to make to get my thing working with version 6.2.0.
=> Keep readme up-to-date for version 6.2.0

hygen.io/docs/quick-start.md
=> Remove extraneous 'new' from quick-start

hygen.io/docs/generators.md, hygen.io/docs/quick-start.md, hygen.io/docs/templates.md
I changed the `[[info]]` blocks with the recommended syntax according to [docusaurus docs](https://docusaurus.io/fr/docs/next/markdown-features/admonitions).
I hope that was the intent. However, the color theme makes `INFO` blocks too shiny 😂.
Fixes #276
=> fix(docs): change [[info]] blocks with correct syntax

README.md, dist/engine.js, dist/help.js, lib/engine.js, lib/help.js, scripts/standalone.js, src/engine.ts, src/help.ts
I found several unsecure links without SSL enabled. Also aligned the url scheme of the hygen homepage referenced in the docs and doc strings across the project. There is one left in the repository description, which is still pointing to **http://hygen.io** which may be changed into **https://hygen.io**, too.
=> docs: fix unsecure links and align format
